## Session 2: Assignment 1
## Task 1.1 
## Write a Python Program to implement your own myreduce() function which works exactly like Python's built-in function reduce()

" " ""
Reduce(f,data)
	Step 1: val1= f(a1,a2)
	Step 2: val2= f(val1,a3)
	Step 3: val3 = f(val2,a4)
	|
	|	
	Step	n-1 : valn-1= f(valn-2,an)
Return valn-1
" " "

In [14]:
# Reduce will produce a single result
def myreduce(func, data):

 # Get first item in sequence and assign to result
  result = data[0]
 # iterate over remaining items in sequence and apply reduction function 
  for item in data[1:]:
   result = func(result, item)

  return result

def sum(x,y): # test Myreduce function
    return x + y
print ("Sum on list [1,2,3] using custom reduce function "   + str(myreduce(sum, [1,2,3])) )


Sum on list [1,2,3] using custom reduce function 6


In [15]:
# Custom filter function 
def myfilter(anyfunc, sequence):

 # Initialize empty list
 result = []
 # iterate over sequence of items in sequence and apply filter function
 for item in sequence:
  if anyfunc(item):
   result.append(item)

 # return funal output
 return result
# test myfilter function
def ispositive(x):
 if (x <= 0): 
  return False 
 else: 
  return True
print ("Filter only positive Integers on list [0,1,-2,3,4,5] using custom filter function"  + str(myfilter(ispositive, [0,1,-2,3,4,5])))

Filter only positive Integers on list [0,1,-2,3,4,5] using custom filter function[1, 3, 4, 5]


In [10]:
def find_longest_word(words_list): # TASK 1.3
    word_len = []
    for n in words_list:
        word_len.append((len(n), n))
    word_len.sort()
    return word_len[-1][1]

print(find_longest_word(["PHP", "Exercises", "Backend"]))

Exercises


In [19]:
lis=['A', 'C', 'A', 'D', 'G', 'I', 'L', ' D']
lis

['A', 'C', 'A', 'D', 'G', 'I', 'L', ' D']

In [30]:
list1=['x', 'xx', 'xxx', 'xxxx', 'y', 'yy', 'yyy', 'yyyy', 'z', 'zz', 'zzz', 'zzzz']
list1

['x', 'xx', 'xxx', 'xxxx', 'y', 'yy', 'yyy', 'yyyy', 'z', 'zz', 'zzz', 'zzzz']

In [22]:
list2=['x', 'y', 'z', 'xx', 'yy', 'zz', 'xx', 'yy', 'zz', 'xxxx', 'yyyy', 'zzzz']
list2

['x', 'y', 'z', 'xx', 'yy', 'zz', 'xx', 'yy', 'zz', 'xxxx', 'yyyy', 'zzzz']

In [24]:
list3=[[2], [3], [4], [3], [4], [5], [4], [5], [6]]
list3

[[2], [3], [4], [3], [4], [5], [4], [5], [6]]

In [25]:
list4=[[2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]]
list4

[[2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]]

In [33]:
list5=[(1, 1), (2, 1), (3, 1), (1, 2), (2, 2), (3, 2), (1, 3), (2, 3), (3, 3)]
list5

[(1, 1), (2, 1), (3, 1), (1, 2), (2, 2), (3, 2), (1, 3), (2, 3), (3, 3)]

In [ ]:
'''Assignment 6.1'''
'''Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.'''

In [8]:
def vander_Input(x,N,order):
    X=x.size
    result_array=np.empty((N,X),dtype=int)
    
    if order.upper()=="TRUE":
        for i in range(N):
            power_vector=np.array(np.power(x,i))
            result_array[i]=power_vector
    else:
        for i in range(N-1,-1,-1):
            power_vector=np.array(np.power(x,i))
            result_array[(N-1)-i]=power_vector
    return result_array

In [9]:
import numpy as np
print('Generate a Vandermonde matrix...')

N=int(input('Enter the value of N power :'))

print('Enter comma separated list of elements eg. 1,2,3 :')
input_vector=input()
input_list=list(map(int,input_vector.split(',')))
x=np.array(input_list)
print('Input vector is :')
print(x)

order=input("Enter 'True' for increasing order of powers else enter 'False' :")

result_array=vander_Input(x,N,order)
print('The resultant Vandermonde matrix is :')
print(result_array.T)

Generate a Vandermonde matrix...
Enter the value of N power :3
Enter comma separated list of elements eg. 1,2,3 :
1,2,3,4
Input vector is :
[1 2 3 4]
Enter 'True' for increasing order of powers else enter 'False' :False
The resultant Vandermonde matrix is :
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


In [1]:
import numpy as np 

In [4]:
np.vander(np.array([1,2,3]))

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [6]:
x = np.array([1,2,4,5])
n=4
print(y)

def vander_mat():
    y=np.vander(x,n, increasing=False)
    return y

NameError: name 'y' is not defined